import type { Metadata } from 'next';
import { Suspense } from 'react';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import { UserAuthData } from '@/components/auth/components/user-data/user-auth-data';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={null}>
          <UserAuthData />
        </Suspense>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
