import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import IsAuth from '@/components/auth/is-auth';
import { endpoints } from '@/lib/constants/endpoints';
import { apiServerService } from '@/lib/services/api/server';
import { UserResponse } from '../../interfaces/user';
import { AUTH_FAILED } from '@/lib/constants/messages';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let user = null;

  try {
    const response = await apiServerService.get<UserResponse>(
      `${endpoints.user.base}${endpoints.user.getUser}`
    );

    if (!response.user) {
      throw new Error(AUTH_FAILED);
    }

    user = response.user;
  } catch {}

  return (
    <html lang="en">
      <body>
        <IsAuth user={user} />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
